<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class DailyReportSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $pastDay1 = Carbon::today()->addDays(-1)->format('Y-m-d');
        $pastDaytime1 = Carbon::today()->addDays(-1)->format('Y-m-d H:i:s');
        $pastDay2 = Carbon::today()->addDays(-2)->format('Y-m-d');
        $pastDaytime2 = Carbon::today()->addDays(-2)->format('Y-m-d H:i:s');
        $pastDay3 = Carbon::today()->addDays(-3)->format('Y-m-d');
        $pastDaytime3 = Carbon::today()->addDays(-3)->format('Y-m-d H:i:s');
        $pastDay4 = Carbon::today()->addDays(-4)->format('Y-m-d');
        $pastDaytime4 = Carbon::today()->addDays(-4)->format('Y-m-d H:i:s');
        $pastDay5 = Carbon::today()->addDays(-5)->format('Y-m-d');
        $pastDaytime5 = Carbon::today()->addDays(-5)->format('Y-m-d H:i:s');
        $pastDay6 = Carbon::today()->addDays(-6)->format('Y-m-d');
        $pastDaytime6 = Carbon::today()->addDays(-6)->format('Y-m-d H:i:s');
        $pastDay7 = Carbon::today()->addDays(-7)->format('Y-m-d');
        $pastDaytime7 = Carbon::today()->addDays(-7)->format('Y-m-d H:i:s');
        $pastDay8 = Carbon::today()->addDays(-8)->format('Y-m-d');
        $pastDaytime8 = Carbon::today()->addDays(-8)->format('Y-m-d H:i:s');
        $pastDay9 = Carbon::today()->addDays(-9)->format('Y-m-d');
        $pastDaytime9 = Carbon::today()->addDays(-9)->format('Y-m-d H:i:s');
        $pastDay10 = Carbon::today()->addDays(-10)->format('Y-m-d');
        $pastDaytime10 = Carbon::today()->addDays(-10)->format('Y-m-d H:i:s');

        DB::table('daily_reports')->insert([
            [
                'member_id' => 1,
                'date' => $pastDay1,
                'start_work_type' => 1,
                'end_work_type' => 1,
                'attendance_memo' => '一日前は特になし',
                'first_period' => '一日前の一限目は作業できた',
                'second_period' => '一日前の二限目は作業できた',
                'third_period' => '一日前の三限目は作業できた',
                'fourth_period' => '一日前の四限目は作業できた',
                'fifth_period' => null,
                'comment' => '一日前は集中して作業できた',
                'next_schedule' => '一日前の次回は作業をする',
                'mental_condition_score' => 1,
                'physical_condition_score' => 2,
                'submitted_at' => $pastDaytime1,
                'staff_memo' => '一日前はがんばりました',
                'deleted_at' => null,
                'created_at' => $pastDaytime1,
                'updated_at' => $pastDaytime1,
            ],
            [
                'member_id' => 1,
                'date' => $pastDay2,
                'start_work_type' => 2,
                'end_work_type' => 2,
                'attendance_memo' => '二日前は遅刻、早退',
                'first_period' => '二日前の一限目は作業できた',
                'second_period' => '二日前の二限目は作業できた',
                'third_period' => '二日前の三限目は作業できた',
                'fourth_period' => '二日前の四限目は作業できた',
                'fifth_period' => null,
                'comment' => '二日前は集中して作業できた',
                'next_schedule' => '二日前の次回は作業をする',
                'mental_condition_score' => 3,
                'physical_condition_score' => 4,
                'submitted_at' => $pastDaytime2,
                'staff_memo' => '二日前はがんばりました',
                'deleted_at' => null,
                'created_at' => $pastDaytime2,
                'updated_at' => $pastDaytime2,
            ],
            [
                'member_id' => 1,
                'date' => $pastDay3,
                'start_work_type' => 1,
                'end_work_type' => 3,
                'attendance_memo' => '三日前は特になし',
                'first_period' => '三日前の一限目は作業できた',
                'second_period' => '三日前の二限目は作業できた',
                'third_period' => '三日前の三限目は作業できた',
                'fourth_period' => '三日前の四限目は作業できた',
                'fifth_period' => '三日前の五限目は作業できた',
                'comment' => '三日前は集中して作業できた',
                'next_schedule' => '三日前の次回は作業をする',
                'mental_condition_score' => 5,
                'physical_condition_score' => 6,
                'submitted_at' => $pastDaytime3,
                'staff_memo' => '三日前はがんばりました',
                'deleted_at' => null,
                'created_at' => $pastDaytime3,
                'updated_at' => $pastDaytime3,
            ],
            [
                'member_id' => 1,
                'date' => $pastDay4,
                'start_work_type' => 2,
                'end_work_type' => 1,
                'attendance_memo' => '四日前は特になし',
                'first_period' => '四日前の一限目は作業できた',
                'second_period' => '四日前の二限目は作業できた',
                'third_period' => '四日前の三限目は作業できた',
                'fourth_period' => '四日前の四限目は作業できた',
                'fifth_period' => '四日前の五限目は作業できた',
                'comment' => '四日前は集中して作業できた',
                'next_schedule' => '四日前の次回は作業をする',
                'mental_condition_score' => 7,
                'physical_condition_score' => 8,
                'submitted_at' => $pastDaytime4,
                'staff_memo' => '四日前はがんばりました',
                'deleted_at' => null,
                'created_at' => $pastDaytime4,
                'updated_at' => $pastDaytime4,
            ],
            [
                'member_id' => 1,
                'date' => $pastDay5,
                'start_work_type' => 1,
                'end_work_type' => 1,
                'attendance_memo' => '五日前は特になし',
                'first_period' => '五日前の一限目は作業できた',
                'second_period' => '五日前の二限目は作業できた',
                'third_period' => '五日前の三限目は作業できた',
                'fourth_period' => '五日前の四限目は作業できた',
                'fifth_period' => '五日前の五限目は作業できた',
                'comment' => '五日前は集中して作業できた',
                'next_schedule' => '五日前の次回は作業をする',
                'mental_condition_score' => 9,
                'physical_condition_score' => 10,
                'submitted_at' => $pastDaytime5,
                'staff_memo' => '五日前はがんばりました',
                'deleted_at' => null,
                'created_at' => $pastDaytime5,
                'updated_at' => $pastDaytime5,
            ],
            [
                'member_id' => 1,
                'date' => $pastDay6,
                'start_work_type' => 2,
                'end_work_type' => 2,
                'attendance_memo' => '六日前は特になし',
                'first_period' => '六日前の一限目は作業できた',
                'second_period' => '六日前の二限目は作業できた',
                'third_period' => '六日前の三限目は作業できた',
                'fourth_period' => '六日前の四限目は作業できた',
                'fifth_period' => '六日前の五限目は作業できた',
                'comment' => '六日前は集中して作業できた',
                'next_schedule' => '六日前の次回は作業をする',
                'mental_condition_score' => 1,
                'physical_condition_score' => 10,
                'submitted_at' => $pastDaytime6,
                'staff_memo' => '六日前はがんばりました',
                'deleted_at' => null,
                'created_at' => $pastDaytime6,
                'updated_at' => $pastDaytime6,
            ],
            [
                'member_id' => 1,
                'date' => $pastDay7,
                'start_work_type' => 2,
                'end_work_type' => 3,
                'attendance_memo' => '七日前は特になし',
                'first_period' => '七日前の一限目は作業できた',
                'second_period' => '七日前の二限目は作業できた',
                'third_period' => '七日前の三限目は作業できた',
                'fourth_period' => '七日前の四限目は作業できた',
                'fifth_period' => '七日前の五限目は作業できた',
                'comment' => '七日前は集中して作業できた',
                'next_schedule' => '七日前の次回は作業をする',
                'mental_condition_score' => 2,
                'physical_condition_score' => 9,
                'submitted_at' => $pastDaytime7,
                'staff_memo' => '七日前はがんばりました',
                'deleted_at' => null,
                'created_at' => $pastDaytime7,
                'updated_at' => $pastDaytime7,
            ],
            [
                'member_id' => 1,
                'date' => $pastDay8,
                'start_work_type' => 2,
                'end_work_type' => 1,
                'attendance_memo' => '八日前は特になし',
                'first_period' => '八日前の一限目は作業できた',
                'second_period' => '八日前の二限目は作業できた',
                'third_period' => '八日前の三限目は作業できた',
                'fourth_period' => '八日前の四限目は作業できた',
                'fifth_period' => '八日前の五限目は作業できた',
                'comment' => '八日前は集中して作業できた',
                'next_schedule' => '八日前の次回は作業をする',
                'mental_condition_score' => 3,
                'physical_condition_score' => 8,
                'submitted_at' => $pastDaytime8,
                'staff_memo' => '八日前はがんばりました',
                'deleted_at' => null,
                'created_at' => $pastDaytime8,
                'updated_at' => $pastDaytime8,
            ],
            [
                'member_id' => 1,
                'date' => $pastDay9,
                'start_work_type' => 1,
                'end_work_type' => 1,
                'attendance_memo' => '九日前は特になし',
                'first_period' => '九日前の一限目は作業できた',
                'second_period' => '九日前の二限目は作業できた',
                'third_period' => '九日前の三限目は作業できた',
                'fourth_period' => '九日前の四限目は作業できた',
                'fifth_period' => '九日前の五限目は作業できた',
                'comment' => '九日前は集中して作業できた',
                'next_schedule' => '九日前の次回は作業をする',
                'mental_condition_score' => 4,
                'physical_condition_score' => 7,
                'submitted_at' => $pastDaytime9,
                'staff_memo' => '九日前はがんばりました',
                'deleted_at' => null,
                'created_at' => $pastDaytime9,
                'updated_at' => $pastDaytime9,
            ],
            [
                'member_id' => 1,
                'date' => $pastDay10,
                'start_work_type' => 2,
                'end_work_type' => 3,
                'attendance_memo' => '十日前は特になし',
                'first_period' => '十日前の一限目は作業できた',
                'second_period' => '十日前の二限目は作業できた',
                'third_period' => '十日前の三限目は作業できた',
                'fourth_period' => '十日前の四限目は作業できた',
                'fifth_period' => '十日前の五限目は作業できた',
                'comment' => '十日前は集中して作業できた',
                'next_schedule' => '十日前の次回は作業をする',
                'mental_condition_score' => 5,
                'physical_condition_score' => 6,
                'submitted_at' => $pastDaytime10,
                'staff_memo' => '十日前はがんばりました',
                'deleted_at' => null,
                'created_at' => $pastDaytime10,
                'updated_at' => $pastDaytime10,
            ],
            [
                'member_id' => 2,
                'date' => $pastDay1,
                'start_work_type' => 1,
                'end_work_type' => 1,
                'attendance_memo' => '一日前は特になし',
                'first_period' => '一日前の一限目は作業できた',
                'second_period' => '一日前の二限目は作業できた',
                'third_period' => '一日前の三限目は作業できた',
                'fourth_period' => '一日前の四限目は作業できた',
                'fifth_period' => '一日前の五限目は作業できた',
                'comment' => '一日前は集中して作業できた',
                'next_schedule' => '一日前の次回は作業をする',
                'mental_condition_score' => 7,
                'physical_condition_score' => 8,
                'submitted_at' => $pastDaytime1,
                'staff_memo' => '一日前はがんばりました',
                'deleted_at' => null,
                'created_at' => $pastDaytime1,
                'updated_at' => $pastDaytime1,
            ],
            [
                'member_id' => 2,
                'date' => $pastDay2,
                'start_work_type' => 1,
                'end_work_type' => 1,
                'attendance_memo' => '二日前は特になし',
                'first_period' => '二日前の一限目は作業できた',
                'second_period' => '二日前の二限目は作業できた',
                'third_period' => '二日前の三限目は作業できた',
                'fourth_period' => '二日前の四限目は作業できた',
                'fifth_period' => '二日前の五限目は作業できた',
                'comment' => '二日前は集中して作業できた',
                'next_schedule' => '二日前の次回は作業をする',
                'mental_condition_score' => 9,
                'physical_condition_score' => 10,
                'submitted_at' => $pastDaytime2,
                'staff_memo' => '二日前はがんばりました',
                'deleted_at' => null,
                'created_at' => $pastDaytime2,
                'updated_at' => $pastDaytime2,
            ],
        ]);
    }
}
